from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPalette, QColor

palette = QPalette()
white = QColor(224, 224, 224)
palette.setColor(QPalette.Window, QColor(32, 32, 32))
palette.setColor(QPalette.WindowText, white)
palette.setColor(QPalette.Base, QColor(32, 32, 32))
palette.setColor(QPalette.AlternateBase, QColor(48, 48, 48))
palette.setColor(QPalette.ToolTipBase, white)
palette.setColor(QPalette.ToolTipText, white)
palette.setColor(QPalette.Text, white)
palette.setColor(QPalette.Dark, QColor(35, 35, 35))
palette.setColor(QPalette.Shadow, QColor(20, 20, 20))
palette.setColor(QPalette.Button, QColor(32, 32, 32))
palette.setColor(QPalette.ButtonText, white)
palette.setColor(QPalette.BrightText, Qt.red)
palette.setColor(QPalette.Link, QColor(255, 255, 255))
palette.setColor(QPalette.Highlight, QColor(42, 130, 218))
palette.setColor(QPalette.HighlightedText, white)
palette.setColor(QPalette.Disabled, QPalette.Text, QColor(127, 127, 127))
palette.setColor(QPalette.Disabled, QPalette.WindowText, QColor(127, 127, 127))
palette.setColor(QPalette.Disabled, QPalette.HighlightedText, QColor(127, 127, 127))
palette.setColor(QPalette.Disabled, QPalette.ButtonText, QColor(127, 127, 127))
palette.setColor(QPalette.Disabled, QPalette.Highlight, QColor(80, 80, 80))
